spring:
  application:
    name: nest

  datasource:
    url: jdbc:postgresql://localhost:5432/nest
    username: ${POSTGRESQL_USERNAME}
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

chatgpt:
  api-key: ${CHATGPT_API_KEY}

nurigo:
  url: ${NURIGO_URL}
  api-key: ${NURIGO_API_KEY}
  secret-key: ${NURIGO_SECRET_KEY}
