spring:
  application:
    name: nest

  datasource:
    url: jdbc:postgresql://localhost:5432/nest
    username: ${POSTGRESQL_USERNAME}
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
